package HomeHub;

/**
* HomeHub/AlarmHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HOMEH.idl
* Wednesday, 5 April 2017 11:04:16 o'clock BST
*/

public final class AlarmHolder implements org.omg.CORBA.portable.Streamable
{
  public HomeHub.Alarm value = null;

  public AlarmHolder ()
  {
  }

  public AlarmHolder (HomeHub.Alarm initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HomeHub.AlarmHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HomeHub.AlarmHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HomeHub.AlarmHelper.type ();
  }

}
