package HomeHub;


/**
* HomeHub/HOMEH.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HOMEH.idl
* Wednesday, 5 April 2017 11:04:16 o'clock BST
*/

public interface HOMEH extends HOMEHOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
	
}


