package HomeHub;


/**
* HomeHub/HOMEHOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HOMEH.idl
* Wednesday, 5 April 2017 11:04:16 o'clock BST
*/

public interface HOMEHOperations 

// sets the operations 

{
  String name ();
  HomeHub.Alarm[] theLog ();
  void raise_Alarm (HomeHub.Alarm alarm);
  void add_Camera (HomeHub.Alarm aCamera);
  void add_Sensor (HomeHub.Alarm aSensor);
  double getNoZones ();
} 
