package HomeHub;


/**
* HomeHub/HOMEHPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HOMEH.idl
* Wednesday, 5 April 2017 11:04:16 o'clock BST
*/

public abstract class HOMEHPOA extends org.omg.PortableServer.Servant
 implements HomeHub.HOMEHOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_name", new java.lang.Integer (0));
    _methods.put ("_get_theLog", new java.lang.Integer (1));
    _methods.put ("raise_Alarm", new java.lang.Integer (2));
    _methods.put ("add_Camera", new java.lang.Integer (3));
    _methods.put ("add_Sensor", new java.lang.Integer (4));
    _methods.put ("getNoZones", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // HomeHub/HOMEH/_get_name
       {
         String $result = null;
         $result = this.name ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // HomeHub/HOMEH/_get_theLog
       {
         HomeHub.Alarm $result[] = null;
         $result = this.theLog ();
         out = $rh.createReply();
         HomeHub.LogHelper.write (out, $result);
         break;
       }

       case 2:  // HomeHub/HOMEH/raise_Alarm
       {
         HomeHub.Alarm alarm = HomeHub.AlarmHelper.read (in);
         this.raise_Alarm (alarm);
         out = $rh.createReply();
         break;
       }

       case 3:  // HomeHub/HOMEH/add_Camera
       {
         HomeHub.Alarm aCamera = HomeHub.AlarmHelper.read (in);
         this.add_Camera (aCamera);
         out = $rh.createReply();
         break;
       }

       case 4:  // HomeHub/HOMEH/add_Sensor
       {
         HomeHub.Alarm aSensor = HomeHub.AlarmHelper.read (in);
         this.add_Sensor (aSensor);
         out = $rh.createReply();
         break;
       }

       case 5:  // HomeHub/HOMEH/getNoZones
       {
         double $result = (double)0;
         $result = this.getNoZones ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } 

  // CORBA::Object operations
  private static String[] __ids = {
    "IDL:HomeHub/HOMEH:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public HOMEH _this() 
  {
    return HOMEHHelper.narrow(
    super._this_object());
  }

  public HOMEH _this(org.omg.CORBA.ORB orb) 
  {
    return HOMEHHelper.narrow(
    super._this_object(orb));
  }


} 
