package HomeHub;


/**
* HomeHub/LogHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HOMEH.idl
* Wednesday, 5 April 2017 11:04:16 o'clock BST
*/

public final class LogHolder implements org.omg.CORBA.portable.Streamable
{
  public HomeHub.Alarm value[] = null;

  public LogHolder ()
  {
  }

  public LogHolder (HomeHub.Alarm[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HomeHub.LogHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HomeHub.LogHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HomeHub.LogHelper.type ();
  }

}
